backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "public/image"
public_folder: "/image/"
collections:
  - name: "directs"
    label: "Напрямки"
    folder: "src/directs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Назва напрямку", name: "title", widget: "string" }
      - { label: "Зображення", name: "image", widget: "image" }
      - { label: "Опис", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "coaches"
    label: "Тренери"
    folder: "src/coaches"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Напрямок тренера", name: "title", widget: "string" }
      - { label: "Зображення", name: "image", widget: "image" }
      - { label: "Освіта", name: "educationDesc", widget: "string" }
      - { label: "Здобутки", name: "achievementDesc", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }