backend:
  name: git-gateway
  branch: main
media_folder: "media"
publish_mode: editorial_workflow
collections:
  - name: "directs"
    label: "Напрямки"
    folder: "src/directs"
    media_folder: "media/directs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Назва напрямку", name: "title", widget: "string" }
      - { label: "Зображення", name: "image", widget: "image" }
      - { label: "Опис", name: "description", widget: "string" }
  - name: "coaches"
    label: "Тренери"
    folder: "src/coaches"
    media_folder: "media/coaches"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Напрямок тренера", name: "title", widget: "string" }
      - { label: "Зображення", name: "image", widget: "image" }
      - { label: "Освіта", name: "educationDesc", widget: "string" }
      - { label: "Здобутки", name: "achievementDesc", widget: "string" }
